### ISSUE TITLE
Non-static method Ichtrojan\\Otp\\Otp::generate() cannot be called statically

### ISSUE THREAD

**Issue by dtobi59** [ichtrojan/laravel-otp#11]
This was the error I got after adding the package to my laravel, 

**Non-static method Ichtrojan\\Otp\\Otp::generate() cannot be called statically**

**Comment by arslannawaz** [comment]
@dtobi59

`Use Otp;

$otp = new Otp;
$otp_token = $otp->generate('michael@okoh.co.uk', 6, 15);`

**Comment by arslannawaz** [comment]
> This was the error I got after adding the package to my laravel,
> 
> **Non-static method Ichtrojan\Otp\Otp::generate() cannot be called statically**

@dtobi59, here is the solution

Use Otp;

$otp = new Otp;
$otp_token = $otp->generate('michael@okoh.co.uk', 6, 15);

**Comment by wychoong** [comment]
@ichtrojan this issue from 2021 is not fixed, why is it closed? is the commented way is the supported way of using? if so why not update the doc?
