### ISSUE TITLE
Error: Using $this when not in object context

### ISSUE THREAD

**Issue by tomerof** [ichtrojan/laravel-otp#16]
Hello,
When I'm trying to generate the OTP using this method
`Ichtrojan\Otp\Otp::generate($email, 6, 15);`
I'm getting this error
Error: Using $this when not in object context in file /vendor/ichtrojan/laravel-otp/src/Otp.php on line 29

**Comment by samik-os** [comment]
It turns out generate isn't a static function.
This should work.
```
$otp = (new OTP())->generate($email, 6, 15);
dd($otp->token);
```
