### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by sluxzer** [ichtrojan/laravel-otp#18]
Hi there @ichtrojan 

I'd like to know if this package supports Laravel 9?

I try to follow the installation step, but the package seems not discoverable.

I find a number of alternative OTP packages, but I think yours is the simple one that I need.

**Comment by ichtrojan** [comment]
I will work on it this weekend, thank you

**Comment by ichtrojan** [comment]
Hi @sluxzer 

This package isn't tied to any Laravel version, it should work regardless
