### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by wychoong** [ichtrojan/laravel-otp#21]
hi, thanks for creating this simple OTP package. However, several issues are observed

- improper use of Laravel Facade
   see issue #11 
- `otp:clean` command doesn't take in tokens that is expired but never validated before

looking at how multiple PRs with improvements are closed without any comments, are you open for PR?

**Comment by ichtrojan** [comment]
Hello, 

Got rid of Facades but you can send in a PR to fix the OTP clean issue.
