### ISSUE TITLE
Issue in validate function

### ISSUE THREAD

**Issue by nikhil-retire100** [ichtrojan/laravel-otp#27]
I think there is issue in validate() function,
It has token in where condition which results in always same error "OTP does not exist"

I have made some changes to fix this, please check the diff below.

https://www.diffchecker.com/kKWDS6kn/

If everything looks okay, I'll create a PR for this fix.

**Comment by bestiony** [comment]
your change seems cleaner. I don't know if it is that necessary since each time you generate an otp for a user the package deletes any previous ones meaning there will always be one top for each user

> https://github.com/ichtrojan/laravel-otp/blob/a44f419392ec8d3ea93409bdb70a1dbf58426ea2/src/Otp.php#L21

**Comment by nikhil-retire100** [comment]
You are right, It was a miss from my side.
Closing this issue.

**Comment by nikhil-retire100** [comment]
You are right, It was a miss from my side.
Closing this issue.
