### ISSUE TITLE
Error when trying to validate OTP

### ISSUE THREAD

**Issue by Edmonbelchev** [ichtrojan/laravel-otp#30]
`"Carbon\\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in /home/gizfvegg/api.droxnet.com/vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 356"`

I'm getting this error message when I'm trying to use validate method:
`(new Otp)->validate($user->email, $request->token);`

Using Laravel 11.

**Comment by ichtrojan** [comment]
not sure this error is associated with the `validate` method
